# Generated by Django 4.1.3 on 2022-11-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_task_assignee_alter_task_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expired_at",
            field=models.DateField(auto_now=True),
        ),
    ]
