# Generated by Django 4.1.3 on 2022-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_task_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="expired_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
